language: java
jdk: openjdk11
script: true
after_success:
  - mvn clean test
  - mvn jacoco:report
  - mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
env:
  global:
    secure: SVEWl4rKvZHcNHxoLS3AABK796TL56qhTdcpRb0oZPgotusg4jUBYYTXadVQdXvhKdEVUQf2pSMU4Duj3UiXWjs8/CyrQy5IwrGoCAhQFXTnUe2Gfm0Vz48xMf7XBbdvPbkcpA3/FCHNN2WREc/c+K4zUoMxn8WpZ4ulBJYJ2agtx6jmPToCrtvD0LG4ZYp2Z20ooJkJlix6f5K1C6jmGkibtWfBq8PHV36pKqS4t5Rj5LqfJt7Vlub7XvyWgOWeuZVShshKV3pQfiGRCcn2G2RpA3PxmelMbEhIpS2EBrSaAOU0AIxAY36zaSIGVf5O3KWRZ5k7GKps5jOokhUjOBAcpQkKNAR2rTfe2W4JluAPEBks0eDmgWqZ6Yk9DZbz8owh9xJUSWXIut137wFYhXfXGeHLdeTgfpmqsjhTPcYVKr7MjP4TZakH73o5DlBOcSaIHYpCdRqUVDc5b60lo7K6QwPl0czhOmjuFVYHTwRzg6aI+Y6rCTaOSx8r9TRsP2Hgih/6kBUA8kiyrtlR57N7ryACv/LQxIGijm+2kKe0nKV0XnffELLfET3inAH3wV7rAZ6nMJ0oGINq3nvP6Ff4mju4SeT1ZRwNATUiJhj4hel05tUXv51hKYScyi1i2dGgG3xM0PRttzwG4wTN3gn6rtretijTV5VQwiavllU=
